--ESTE SCRITP TEM COMO O OBJETIVO ASSOCIAR O PRODUTO AO GRUPO DE RESTRICAO ATRAVES DO 
-- CAMPO CODIGO DE PRODUTO E O ID_DEF_GRUPO_PRODUTO_RESTRICAO, MAS É NECESSARIO QUE O GRUPO
-- JÁ ETENHA SIDO CRIADO NO SCRIPT 1 - Script - Restricao por Endereco_Grupo.sql
-- Procedure exec stp_produto_endereco_restricao_grava Null, 20303, 23

-- SOMENTE USAR O DELETE CASO SEJA UMA LIMPEZA TOTAL PARA INSERIR DADOS NOVOS
DELETE PRODUTO_DEF_GRUPO_PRODUTO_RESTRICAO DBCC CHECKIDENT(PRODUTO_DEF_GRUPO_PRODUTO_RESTRICAO, RESEED, 1)
GO
DELETE ENDERECO_RESTRICAO DBCC CHECKIDENT(ENDERECO_RESTRICAO, RESEED, 1)
GO

BEGIN TRAN;
--INSERIR DADOS NA TABELA PRODUTO_DEF_GRUPO_PRODUTO_RESTRICAO
INSERT PRODUTO_DEF_GRUPO_PRODUTO_RESTRICAO (COD_PRODUTO,ID_DEF_GRUPO_PRODUTO_RESTRICAO)
SELECT COD_PRODUTO,ID_DEF_GRUPO_PRODUTO_RESTRICAO
FROM MIG_ENDERECO_RESTRICAO
COMMIT ;