--VALIDACOES INICIAIS
-- Verificar se existe o endereço
SELECT * FROM endereco where id_endereco=3978

-- Vriricar se existe saldo para o produto no endereço e na OL
SELECT * FROM vw_lote_estoque where id_endereco=3978 and cod_produto = 3

--verificar se existe o lote
select * from lote where id_lote = 697

-- Verificar se tem codigo de barras para o produto
SELECT * FROM CAIXA_FECHADA where cod_produto = 3


-- ACOES EXECUTADAS
--CRIADO O CENTRO DE DISTRIBUIÇÃO NOVO
select * from centro_distribuicao
insert centro_distribuicao values (37170,'FILIAL_GV',NULL)
--update centro_distribuicao set descricao = 'MATRIZ_EXPED_ALMOX' where cod_distribuicao = 1

--CRIADO UM NOVO REGISTRO DA param_estoque PARA O NOVO CD
SELECT * FROM param_estoque

INSERT param_estoque
SELECT 37170,Modelo_Etiqueta_CF,vinculo_lote_fracionado,rf_encerra_volumes_cf,
qtd_lacres,rf_foco_campo_quantidade,controle_caixa_retornavel,id_endereco_finalizacao,imprime_picking_pallet,
ordena_picking_cf_zig_zag,apenas_endereco_sugerido,usa_convocacao_ativa,finaliza_volume_checkout,
nivel_quebra_cf_zig_zag,habilita_cadastro_rf,habilita_pedido_pendente,mov_default,imprime_picking_cf,
entrada_n_pedidos,habilita_mov_todos_estocagem,confirma_lote_separacao_CF,
permite_n_lote_produto_mesmo_endereco,prazo_limpa_cod_prenota,reordena_volume,orderm_imp_cf,
cod_situacao_lote_entrada,habilita_cod_checkout,habilita_qte_checkout,corte_bloqueia_endereco_segragado,
separacao_CF_somente_endereco_fixo,habilita_checkout_por_endereco,separacao_FR_somente_flowrack,
habilita_fantasia_entidade,max_limite_validade_vencida,bloqueia_digitacao_carregamento,habilita_impressao_etiqueta_unitaria,
seleciona_picking_agrupada,habilita_checkin,quantidade_padrao_checkin,bloqueia_alteracao_lote,dias_lote_historico,habilita_multi_conferente,
reabastecimento_expresso,habilita_peso_variavel,encerra_volume_embarque,armazenagem_express,banco_expurgo,habilita_peso,picking_faixa_end,
habilita_movimentacoes_classif,endereco_padrao_corte,exportacao_antecipada,habilita_movimento_log,habilita_finalizacao_agrupada,
dias_de_estoque_para_fixo,dias_de_estoque_default,dias_calculo_media_venda,permite_armazenar_mercadoria_sem_inventario_finalizado,
testa_quantidade_lote,endereco_padrao_PutToLight,bloqueia_alteracao_validade_lote,separar_somente_flowrack,
qtd_max_limite_onda,integra_separacao_automatizada,obriga_transp_ger_onda,nao_controla_estoques,impressao_etiquetas_default,
obriga_digitar_data_saida,impressao_picking_default,controla_sobra,nao_confere_entrada_tranf_oper,hab_corte_produto,hab_corte_produtos_pendentes,
hab_corte_total,hab_corte_separado,varios_produtos_endereco,separacao_CF_lote_by_pass,reabastecimento_somente_endereco_fixo,
job_reabastecimento_pelo_fixo,conferir_palletizando,habilita_LPN,permite_n_lote_produto_mesma_LPN,permite_n_produto_mesma_LPN,habilita_senha_corte,
controla_area_movimentacao,controla_area_movimentacao_destino,permite_n_enderecos_flowarck_por_porduto,Permite_Numero_Lacre_container,
Permite_embarcar_pedido_mais_container,permite_entrega_container_fora_rota,Permite_receber_sem_agendamento,meta_unidades_checkout,
define_separado,visualiza_lote_rf,obriga_dupla_conferencia_numero_serie,controla_volume_checkout,permite_armazenar_lpn_lastro_completo,
separacao_container_somente_picking,mostra_msg_finaliza_RFAPP,separacao_automatica_picking_fr,meta_total_unidades_checkout,
nao_atualiza_emb_produto,varios_fixos_por_flowrack,cancelamento_automatico_pedido,habilita_checkout_split,max_usuarios_colmeia,
imprime_pedido_item_sem_endereco,bloqueia_inv_fixo_nao_associado,bloqueia_inv_flowrack_nao_associado,RFCE_habilita_corte_coleta,
RFCE_abater_estoque,RFCE_mesmo_de_origem,bloqueia_digitacao_ean_checkout,permite_n_produtos_por_flowrack,separacao_rfapp_obriga_checkout,
exibe_produto_rel_separacao_rf,exibe_produto_separacao_rf,exige_lpn_separacao_rf,visualiza_QMS_rfapp,valida_separacao_fracionada_finalizacao,
divide_volumes_por_quantidade,quantidade_divisao_volumes,endereco_retorno_pedido_cancelamento,auditoria_por_produto_rf,
separacao_habilita_checkout_automaticamente,separacao_automatica_picking_fr_lpn_rf,quantidade_maxima_envios,cria_pedido_intermediario,
rfapp_habilta_endereco_transitorio,finaliza_volume_ponto_final,obriga_linha_procura_pedido,controla_exportacao_flowrack,obriga_conferencia_pedido_nf,
meta_separacao_CF,meta_expedicao,tipo_ordenacao_pn,id_endereco_cancelamento,exibe_msg_geracao_onda,imprime_etiqueta_embarque_tela_Finalizacao,
sequencial_sorter,meta_unidades_decanting,meta_total_unidades_decanting,meta_total_decantings,meta_decantings,meta_total_packing,meta_media_packing,
integra_conferencia_por_snapshot,separacao_endereco_intermediario,meta_media_conferencia,seleciona_picking_agrupada_manual,realiza_split_wms,
gerar_onda_considera_estoque_em_movimentacao,rfapp_separacao_bloqueia_digitacao_quantidade,conferencia_pedido_bloqueia_digitacao_quantidade,
rfapp_separacao_permite_troca_endereco,conferencia_pedido_confirma_volume,utiliza_caixa_padrao_secundaria,box_separacao_obrigatorio,utiliza_separacao_bulk_picking,
alerta_inferior_tempo_conf_kpi_recebimento,alerta_superior_tempo_conf_kpi_recebimento,imprime_etiqueta_somente_cf,valida_numero_serie_separacao,
confere_numero_serie_saida,bloqueia_conferente_mesmo_endereco_agrupamento_inventario,associa_produto_a_todas_operacoes_logisticas,id_mascara_rastreio_default,
bloqueia_endereco_finalizacao,rota_transportadora,gera_onda_bloqueada,utiliza_consolidacao_pedidos,valida_numero_serie_conferencia,packing_checkout,
digita_quantidade_checkout,libera_volume_sem_entrega,libera_carregamento_erp,libera_somente_documento,utiliza_multipla_volumetria,cria_consolidacao,
utiliza_validacao_por_rastreabilidade,exibe_sugestao_armazenagem_lote,permite_mudar_lote_endereco,obriga_motivo_movimentacao,permite_voltar_liberado_pedido_corte,
utiliza_lpn_origem_separacao,volume_fracao_por_lote,bloqueia_n_lote_mesmo_endereco,exibe_informacao_produto_etiqueta,permite_separacao_a_maior,
id_endereco_envelhecimento,permite_armazenar_mercadoria_sem_conferencia_finalizada,utiliza_lpn_origem_bulk_picking,divisao_volume,
encerra_volume_bulk_picking,encerra_volume_agrupamento,finaliza_pedido_agrupado_separacao,altera_lote_bulk_picking_num_serie,usa_id_pai_kanban,
finaliza_container_bulk_picking,separacao_CF_somente_endereco_picking,encerra_volume_expedicao,obriga_selecionar_lpn,finaliza_lpn_cod_pedido_polo,
bloqueia_digitacao_armazenamento_RFCE,bloqueia_digitacao_reabastecimento_RFCE,bloqueia_digitacao_movimentacao_RFCE,bloqueia_digitacao_saida_RFCE 
FROM param_estoque


-- CRIA UM GRUPO DE OL
SELECT * FROM grupo_operacao_logistica
INSERT INTO grupo_operacao_logistica VALUES ('FILIAL_GV',37170)
Update grupo_operacao_logistica set descricao = 'MATRIZ_EXPED_ALMOX' where cod_grupo_operacao_logistica = 1


-- DUPLICA OS DADOS DA PARAM_OPERACAO
insert param_operacao
select 37170,operacao,cubagem,checkout,id_relatorio_movimento,cod_etiqueta_fracao,cod_etiqueta_CF,bloqueia_lote_vencido,
obriga_gerar_romaneio,id_relatorio_reabastecimento_fixo,volume_fracao_por_unidade,volume_pos_separacao,obriga_pesar_pedidos,
separacao_multiplos_box,volume_fracao_por_lote,obriga_exportar_container 
from param_operacao



-- UPDATE NA operacao_logistica PARA QUE O CAMPO cod_distribuicao SEJA O NOVO CENTRO DE DISTRIBUICAO CRIADO
select * from operacao_logistica
--
update operacao_logistica set 
cod_distribuicao = 37170,
cod_grupo_operacao_logistica = 2
where cod_operacao_logistica = 37170

SELECT * FROM ENTIDADE WHERE cod_tipo = 14