DECLARE 
@DISK VARCHAR(200)

SELECT @DISK = 'F:\Backup\'+'JOKR-BD01_WMSRX_DAKI_PRE_LIMPEZA_FULL' 
+ CONVERT(NVARCHAR(20),GETDATE(),112) + '_' + REPLACE(CONVERT(NVARCHAR(20),GETDATE(),108),':','') + '.BAK' 

print @DISK

BACKUP DATABASE WMSRXDaki TO  DISK = @DISK WITH NOFORMAT, INIT,
NAME = N'WMSRX-Backup JOKR-BD01_WMSRX_DAKI_PRE_LIMPEZA_FULL', SKIP, NOREWIND, NOUNLOAD, STATS = 10
GO

--versao
--2022.1.6