USE master;  
GO  

ALTER DATABASE WMSRXDaki SET OFFLINE WITH ROLLBACK IMMEDIATE 
GO


RESTORE DATABASE WMSRXDaki 
FILE = N'DisbbyBase_Data' 
FROM  DISK = N'F:\Backup\JOKR-BD01_WMSRXDaki_PRE_ATUALIZACAO20230322_120506.BAK' 
WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 10
GO

ALTER DATABASE WMSRXDaki SET ONLINE
GO
