SELECT DISTINCT PR.COD_PRODUTO AS COD_PROD_REL,MK.COD_SKU AS COD_PROD_KANBAN
FROM PRODUTO_RELACIONADO PR
RIGHT JOIN MIG_KANBAN_TRABALHO MK ON PR.COD_PRODUTO_REL*10 + DBO.CALCDIGITOMOD11(PR.COD_PRODUTO_REL) = MK.COD_SKU
WHERE PR.COD_PRODUTO IS NULL