DECLARE 
@DISK VARCHAR(200)

SELECT @DISK = 'E:\Backup\SaoCamilo\DB01$SAOCAMILO\WMSRX\FULL\'+'DB01_WMSRX_SAOCAMILO_FULL_PRE_LIMPEZA' 
+ CONVERT(NVARCHAR(20),GETDATE(),112) + '_' + REPLACE(CONVERT(NVARCHAR(20),GETDATE(),108),':','') + '.BAK' 

print @DISK

BACKUP DATABASE WMSRX_HML TO  DISK = @DISK WITH NOFORMAT, INIT,
NAME = N'WMSRX-BKP__SAOCAMILO_FULL_PRE_LIMPEZA', SKIP, NOREWIND, NOUNLOAD, STATS = 10
GO